django_project-announcement-web/announcements/announcements/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

django_project-announcement-web/announcements/main/urls.py
from django.urls import path
from .views import get_user_announcement_list, get_user_announcement_list_by_id, create_announcement, get_public_announcements, get_local_announcements, get_announcement_by_id, update_announcement, delete_announcement, register, user_login, home, user_logout

urlpatterns = [
    path('announcements/public', get_public_announcements, name='get_public_announcements'),
    path('announcements/local', get_local_announcements, name='get_local_announcements'),
    path('announcements/create', create_announcement, name='create_announcement'),
    path('announcements/user/',  get_user_announcement_list, name='get_user_announcement'),
    path('announcement/<int:id>/update', update_announcement, name='update_announcement'),
    path('announcement/<int:id>/delete', delete_announcement, name='delete_announcement'),
    path('announcement/<int:id>/', get_announcement_by_id, name='get_announcement_by_id'),
    path('announcements/all/<int:id>/', get_user_announcement_list_by_id, name='get_user_announcement_list_by_id'),
   
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('', home, name='home'),
]



    

django_project-announcement-web/announcements/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    location = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.username


class Announcement(models.Model):
    ACCESS_CHOICES = (
        ('public', 'Public'),
        ('local', 'Local'),
    )

    subject = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    content = models.TextField()
    access = models.CharField(max_length=6, choices=ACCESS_CHOICES, default='public')
    location = models.CharField(max_length=255, blank=True, null=True)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

django_project-announcement-web/announcements/templates/announcement/announcement.html
{% extends 'base.html' %}
{% block title %}
Announcement Details
{% endblock title %}

{% block body %}
<style>
    .root_card {
        margin: 30px auto;
        width: fit-content;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 25px;

        border-radius: 8px;
        background: #fff;

        box-shadow: 0px 4px 25px 0px rgba(0, 0, 0, 0.1);
    }

    .root_card ul {
        display: flex;
        flex-direction: column;

    }

    .root_card li {
        display: grid;
        grid-template-columns: 1.5fr 2fr;
        font-size: 18px;
    }

    .root_card h2 {
        color: #023E8A;
        margin-bottom: 45px;
    }
</style>

<div className="wrapper_center">
    <div className="root_card">
        <h2>Announcement Details</h2>

        <ul>
            <li>
                <strong>Title:</strong>
                <p>{{ announcement.title }}</p>
            </li>
            <li>
                <strong>Content:</strong>
                <p>{{ announcement.content }}</p>
            </li>
            <li>
                <strong>Access:</strong>
                <p>{{ announcement.access }}</p>
            </li>
            <li>
                <strong>Location:</strong>
                <p>{{ announcement.location }}</p>
            </li>
            <li>
                <strong>Created by:</strong>
                <p>{{ announcement.user_profile.username }}</p>
            </li>
            <li>
                <strong>Created at:</strong>
                <p>{{ announcement.create_date }}</p>
            </li>
        </ul>
    </div>
</div>
{% endblock body%}

django_project-announcement-web/announcements/templates/announcement/create_announcement.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <title>Document</title>
  {%load static%}
  <link rel="stylesheet" href="{%static 'create.css' %}">
</head>

<body>
  <header>
    <div className="top-menu">
      <h1 className="title">Announcements Web</h1>
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/announcements/public">Public List</a></li>
        {% if user.is_authenticated %}
        <li>
          <a href="/announcements/local">Local List</a>
        </li>
        <li>
          <a href="/announcements/user">User List</a>
        </li>
        <li>
          <a href="/announcements/create">Create</a>
        </li>
        {% endif %}


        {% if user.is_authenticated %}
        <li className="access side dropdown">
          <a className="nav-link dropdown-toggle action_link" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
          <div className="dropdown-menu" aria-labelledby="navbarDropdown">
            <a className="dropdown-item logout" href="/logout">Logout</a>
          </div>
        </li>
        {% else %}
        <li className="access side"><a href="/login">Log In</a></li>
        <li className="access"><a href="/register">Register</a></li>
        {% endif %}


      </ul>
    </div>
  </header>
  <main>
    <div className="block"></div>
    <div className="form_container">
      <form id="create-form">
        {% csrf_token %}
        <h2 className="form_title">Create Announcement</h2>
        <label htmlFor="subject">Subject</label>
        <input type="text" id="subject" name="subject">
        <label htmlFor="title">Title</label>
        <input type="text" id="title" name="title">
        <label htmlFor="content">Content</label>
        <textarea name="content" cols="40" rows="10" required="" id="id_content" style="height: 101px;"></textarea>
        <label htmlFor="content">Access</label>
        <select name="access" id="id_access">
          <option value="public" selected="">Public</option>
          <option value="local">Local</option>
        </select>
        <input type="submit" value="Create Announcement">
      </form>
      <img src="../static/img/create_announcement.jpg" className="registration-img">
    </div>
    <span className="pencil">✎</span>
    <span className="message"></span>
    <span className="horn">📢</span>
  </main>
</body>
<script src="{%static 'create.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
  </script>

</html>

django_project-announcement-web/announcements/templates/announcement/list_of_local_announcements.html
{% extends 'base.html' %}

{% block title %}
Local Announcements
{% endblock title %}

{% block body %}
<style>
    .root_list {
        margin: 30px auto;
        width: 85vw;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 25px;


        border-radius: 8px;
        background: #FFF;

        box-shadow: 0px 4px 25px 0px rgba(0, 0, 0, 0.10);
    }

    h1 {
        color: #023E8A;
        margin-bottom: 25px;
    }

    .list li {
        width: 100%;
        display: grid;
        grid-template-columns: repeat(6, 1fr);
        gap: 10px;
        font-weight: 500;
        font-size: 18px;
        padding: 7px 10px;
    }

    .list a {
        text-align: end;
    }

    li span,
    li strong {
        color: #023E8A;
    }

    .column_title span {
        font-weight: 700;
    }

    .column_title {
        background: rgba(163, 211, 255, 0.961) !important;
    }

    .title {
        margin-left: 10px;
    }

    .content {
        margin-left: -10px;
    }

    .access {
        margin-left: -10px;
    }

    .author {
        margin-left: 40px;
    }

    .date {
        margin-left: 60px;
    }

    .actions {
        text-align: end;
        margin-right: 20px;
    }

    .list {
        padding: 0;
    }

    .list li:nth-child(even) {
        background: rgba(190, 224, 254, 0.28)
    }

    .list li:nth-child(odd) {
        background: rgba(163, 211, 255, 0.461);
    }
</style>

<div className="wrapper_center">
    <div className="root_list">
        <h1>{{ location }}</h1>

        {% if announcements %}
        <ul className="list">
            <li class="column_title">
                <span class="title">Title</span>
                <span class="content">Content</span>
                <span class="access">Access</span>
                <span class="author">Author</span>
                <span class="date">Date</span>
                <span class="actions">Actions</span>
            </li>
            {% for announcement in announcements %}
            <li>
                <strong>{{ announcement.title }}</strong>
                <span>{{ announcement.content }}</span>
                <span>{{ announcement.access }}</span>
                <span>Created by: {{ announcement.user_profile.username }}</span>
                <span>{{ announcement.create_date }}</span>
                <a href="/announcement/{{ announcement.id }}/">View Details</a>
                <!-- Add any other fields you want to display -->
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No local announcements available for this location.</p>
        {% endif %}
    </div>
</div>
{% endblock body %}

django_project-announcement-web/announcements/templates/announcement/list_of_public_announcements.html
{% extends 'base.html' %}
{% block title %}
Public Announcements
{% endblock title %}
{% block body %}
<style>
  .root_list {
    margin: 30px auto;
    width: 85vw;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 25px;


    border-radius: 8px;
    background: #FFF;

    box-shadow: 0px 4px 25px 0px rgba(0, 0, 0, 0.10);
  }

  .list li {
    width: 100%;
    display: grid;
    grid-template-columns: repeat(6, 1fr);
    gap: 10px;
    font-weight: 500;
    font-size: 18px;
    padding: 7px 10px;
  }

  .list a {
    text-align: end;
  }

  .actions {
    text-align: end;
    margin-right: 20px;
  }

  h2 {
    color: #023E8A;
    margin-bottom: 25px;
  }

  .column_title span {
    font-weight: 700;
  }

  .column_title {
    background: rgba(163, 211, 255, 0.961) !important;
  }

  .author {
    margin-left: 40px;
  }

  .date {
    margin-left: 65px;
  }

  .content {
    margin-left: -10px;
  }

  .access {
    margin-left: -5px;
  }

  .title {
    margin-left: 10px;
  }

  li span,
  li strong {
    color: #023E8A;
  }

  .list {
    padding: 0;
  }

  .list li:nth-child(even) {
    background: rgba(190, 224, 254, 0.28)
  }

  .list li:nth-child(odd) {
    background: rgba(163, 211, 255, 0.461);
  }
</style>
<div className="wrapper_center">
  <div className="root_list">
    <h2>Announcement Detail</h2>

    <ul className="list">
      <li class="column_title">
        <span class="title">Title</span>
        <span class="content">Content</span>
        <span class="access">Access</span>
        <span class="author">Author</span>
        <span class="date">Date</span>
        <span class="actions">Actions</span>
      </li>
      {% for announcement in announcements %}
      <li>
        <strong>{{ announcement.title }}</strong>
        <span>{{ announcement.content }}</span>
        <span>{{ announcement.access }}</span>
        <span>Created by: {{ announcement.user_profile.username }}</span>
        <span>{{ announcement.create_date }}</span>
        <a href="/announcement/{{ announcement.id }}/">View Details</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock body %}

django_project-announcement-web/announcements/templates/announcement/list_of_user_announcements.html
{% extends 'base.html' %}

{% block title %}
User Announcements
{% endblock title %}

{% block body %}
<style>
    .root_list {
        margin: 30px auto;
        width: 75vw;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding: 25px;


        border-radius: 8px;
        background: #FFF;

        box-shadow: 0px 4px 25px 0px rgba(0, 0, 0, 0.10);
    }

    h2 {
        color: #023E8A;
        margin-bottom: 25px;
    }

    .column_title span {
        font-weight: 700;
    }

    .column_title {
        background: rgba(163, 211, 255, 0.961) !important;
    }

    .list li {
        width: 100%;
        display: grid;
        grid-template-columns: repeat(3, 2fr) repeat(2, 3fr) repeat(3, 1fr);
        gap: 10px;
        font-weight: 500;
        font-size: 18px;
        padding: 7px 10px;
    }

    .list a {
        text-align: end;
    }

    li span,
    li strong {
        color: #023E8A;
    }

    .title {
        margin-left: 10px;
    }

    .content {
        margin-left: -10px;
    }

    .access {
        margin-left: -5px;
    }

    .author {
        margin-left: 40px;
    }

    .date {
        margin-left: 60px;
    }

    .list {
        padding: 0;
    }

    .list li:nth-child(even) {
        background: rgba(190, 224, 254, 0.28)
    }

    .list li:nth-child(odd) {
        background: rgba(163, 211, 255, 0.461);
    }
</style>


<div className="wrapper_center">
    <div className="root_list">
        <h2>Your Announcements</h2>

        <ul className="list">
            <li class="column_title">
                <span class="title">Title</span>
                <span class="content">Content</span>
                <span class="access">Access</span>
                <span class="author">Author</span>
                <span class="date">Date</span>
                <span></span>
                <span class="actions">Actions</span>
            </li>
            {% for announcement in announcements %}
            <li>
                <strong>{{ announcement.title }}</strong>
                <span>{{ announcement.content }}</span>
                <span>{{ announcement.access }}</span>
                <span>Created by: {{ announcement.user_profile.username }}</span>
                <span>{{ announcement.create_date }}</span>
                <a href="/announcement/{{ announcement.id }}/update">Edit</a>
                <a href="/announcement/{{ announcement.id }}/">Open</a>
                <a href="/announcement/{{ announcement.id }}/delete">Delete</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock body%}

django_project-announcement-web/announcements/templates/announcement/update_announcement.html
{% extends 'base.html' %}

{% block title %}
User Announcements
{% endblock title %}

{% block body %}
<style>
  .root_update {
    margin: 30px auto;
    width: fit-content;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 25px;

    border-radius: 8px;
    background: #fff;

    box-shadow: 0px 4px 25px 0px rgba(0, 0, 0, 0.1);
  }

  input {
    width: 100%;
  }

  form {
    width: 100%;
  }

  form>p {
    width: 100%;
  }

  h2 {
    color: #023E8A;
    margin-bottom: 25px;
  }

  label {
    color: #023E8A;
    font-weight: 600;
  }

  form input {
    color: #023E8A;
    border-color: #023E8A;
  }

  textarea {
    border-color: #023E8A;
    color: #023E8A;
    padding-left: 2px;
    height: 100px;
    width: 100%;
  }

  select {
    border-color: #023E8A;
  }

  option {
    color: #023E8A;
    ;
  }

  .mBtn {
    border-color: unset;
  }
</style>

<div className="wrapper_center">
  <div className="root_update">
    <h2>Your Announcements</h2>

    <form method="post" action="{% url 'update_announcement' id=announcement.id %}">
      {% csrf_token %}
      <label htmlFor="title">Title:</label>
      <input type="text" id="title" name="title" value="{{ announcement.title }}" required><br>
      <label htmlFor="content">Content:</label>
      <textarea id="content" name="content" required>{{ announcement.content }}</textarea><br>
      <label htmlFor="access">Access:</label>
      <select id="access" name="access">
        <option value="public" {% if announcement.access=='public' %}selected{% endif %}>Public</option>
        <option value="local" {% if announcement.access=='local' %}selected{% endif %}>Local</option>
      </select><br>
      <button className="mBtn" type="submit">Update</button>
    </form>
  </div>
</div>
{% endblock body%}